openapi: 3.0.0
info:
  title: My API
  description: API for my application
  version: 1.0.0
paths:
  /users:
    get:
      description: Returns all users
      responses:
        200:
          description: OK
